model = "gpt-5"
model_provider = "openai"

preferred_auth_method = "chatgpt"

sandbox_mode = "workspace-write"
approval_policy = "on-request"

[tools]
web_search = true

[sandbox_workspace_write]
network_access = true

[mcp_servers.deepwiki]
command = "npx"
args = ["-y", "mcp-remote", "https://mcp.deepwiki.com/mcp"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "mcp-remote", "https://mcp.context7.com/mcp"]

[mcp_servers.playwright]
command = "npx"ß
args = ["-y", "@playwright/mcp@latest"]